### ISSUE TITLE
Uncaught (in promise) ReferenceError: position is not defined

### ISSUE THREAD

**Issue by Gorbov** [chenjuneking/quill-image-drop-and-paste#1]
Hi!

I've got an error with latest Quill 1.3.6:
```
filepond.js:8694 Uncaught (in promise) ReferenceError: position is not defined
    at Object.root.ref.paster.onload (filepond.js:8694)
    at cb (filepond.js:7929)
    at filepond.js:7894
    at Array.forEach (<anonymous>)
    at filepond.js:7893
```

Any ideas how to fix it?

**Comment by chenjuneking** [comment]
it seems the third party module cause this problem, can you post more details about this?
By the way, I didnot use this  module on my dependence, maybe you should ask for help from this repos:
https://github.com/pqina/filepond
