### ISSUE TITLE
No license defined

### ISSUE THREAD

**Issue by eG-dev** [chenjuneking/quill-image-drop-and-paste#13]
Hi guys, thanks for provision of this helpful package!

Unfortunately, there is no indication of the license. This means, in legal terms, that the use of the package is basically prohibited. No matter whether in a private or commercial environment.

I would like to use the package in one of my projects, but I can't because of the restriction described above.

Could you please add the information about the license?

Here are a few suggestions about the possible license:
https://opensource.org/licenses/MIT
https://opensource.org/licenses/ISC
https://opensource.org/licenses/Apache-2.0

**Comment by chenjuneking** [comment]
> Hi guys, thanks for provision of this helpful package!
> 
> Unfortunately, there is no indication of the license. This means, in legal terms, that the use of the package is basically prohibited. No matter whether in a private or commercial environment.
> 
> I would like to use the package in one of my projects, but I can't because of the restriction described above.
> 
> Could you please add the information about the license?
> 
> Here are a few suggestions about the possible license:
> https://opensource.org/licenses/MIT
> https://opensource.org/licenses/ISC
> https://opensource.org/licenses/Apache-2.0

@eG-dev Thanks for your PR, feel free to use the package;)
