### ISSUE TITLE
Paste not working

### ISSUE THREAD

**Issue by alexkingdom** [chenjuneking/quill-image-drop-and-paste#16]
Hey guys, I'm using vue and it's 100% as in your example.
All works except when copy / paste the file.
Used Latest Firefox & Google Chrome.

Drang & Drop is working good.
Can't find whats is wrong. Can you guys look at this ?

**Comment by cramy25** [comment]
same here, have you been able to find a solution?
I tried, firefox, chrome and edge, all the time the same result.

Could you guys please have a look?

**Comment by alexkingdom** [comment]
@cramy25 didn't have time to find a solution. But if you will find a fast way, please let me know.

**Comment by chenjuneking** [comment]
hi, @alexkingdom and @cramy25 .
copy / paste in this plugin exactly means paste the images' data which stored in the clipbaord, for example, you can catch your screen's snapshot by press the 'Prt Sc Sys Rq' key on your keyboard, and focus on the editor, then paste the image. Some App like wechat or slask, which support cut your screenshot, will save part of your screen in the clipbaord. 
But not the scene that copy the image on your disk and paste it into the editor, for the browser's policy, web application would not allow to access user's file, but you could do that by some platform like [electron](https://www.electronjs.org/) which integrate node.js that was able to read / write user's local file.

**Comment by alexkingdom** [comment]
@chenjuneking you are right, just checked. This is working good. It's my bad.
If for @cramy25 is also all ok with this, then this issue can be closed.

Thank you and sorry :)

**Comment by cramy25** [comment]
ok noted, sounds good for me as well
