### ISSUE TITLE
url image

### ISSUE THREAD

**Issue by cramy25** [chenjuneking/quill-image-drop-and-paste#17]
Hi, is there a way to enhance this plug in with the paste of image URL?

It will make it a complete plugin

**Comment by chenjuneking** [comment]
> Hi, is there a way to enhance this plug in with the paste of image URL?
> 
> It will make it a complete plugin

Hi @cramy25 , could you apply more details?

**Comment by cramy25** [comment]
Hi @chenjuneking something like this [https://github.com/quilljs/quill/issues/893], but look like the solution is not that easy

**Comment by chenjuneking** [comment]
> Hi @chenjuneking something like this [https://github.com/[quilljs/quill/issues/893](https://github.com/quilljs/quill/issues/893)], but look like the solution is not that easy

Good idea, this will be the next feature.

**Comment by chenjuneking** [comment]
This feature has been release on v1.2.0.
