### ISSUE TITLE
TypeError: Cannot read property 'register' of undefined

### ISSUE THREAD

**Issue by Siihyun** [chenjuneking/quill-image-drop-and-paste#18]
Hi, I think there are some errors in this version. when I'm trying to apply this line, 
Quill.register("modules/imageDropAndPaste", QuillImageDropAndPaste); 
an error is occured.

![image](https://user-images.githubusercontent.com/44644821/117539660-99d4ee00-b046-11eb-8bde-50dd7b4f3511.png)

And react-demo example didn't work properly as well. 
![image](https://user-images.githubusercontent.com/44644821/117539716-dbfe2f80-b046-11eb-9b7b-04e58771b213.png)

Can you check it?
Thanks.

**Comment by chenjuneking** [comment]
Hi @Siihyun , the issue has been fixed on v1.2.1

Thanks!

**Comment by Siihyun** [comment]
Thanks for your quick answer. And I've modified the version in react-demo to v1.2.1.
Thanks!
