### ISSUE TITLE
set cursor at the end of the sentence after copy & paste

### ISSUE THREAD

**Issue by Siihyun** [chenjuneking/quill-image-drop-and-paste#24]
Hi. I have some issues using quill editor.

Is it possible to move cursor at the end of the sentence after user wrote something by copy & paste?(ctrl+v or command+v)
Now it remains at the first of sentence.

Thanks

**Comment by chenjuneking** [comment]
try this:
```
let index = (quill.getSelection() || {}).index;
if (index === undefined || index < 0) index = quill.getLength();
quill.insertEmbed(index, 'image', image_url, 'user')
quill.setSelection(index + 1)
```

**Comment by chenjuneking** [comment]
I also publish this feature to the version v1.2.4, thanks!

**Comment by Siihyun** [comment]
Cool! Thanks for you fast response.

Actually, I mean for text, not for image.
So I requested PR just before.

Take a look and let me know if there's a better way.
Thanks.

**Comment by Siihyun** [comment]
Cool! Thanks for your fast response.

Actually, I mean for the text, not for the image.
So I created a PR just before.

Take a look and let me know if there's a better way.
Thanks.

**Comment by chenjuneking** [comment]
Thanks for your PR, really nice works!
 I add comment for it, please update  then I could merge it.

**Comment by Siihyun** [comment]
Ok. But I can't see any comment now. Could you check it again?

**Comment by chenjuneking** [comment]
I had update my comment, can you see it now?

**Comment by Siihyun** [comment]
Yes. I updated it. Thanks

**Comment by chenjuneking** [comment]
Since the PR has been merged, I closed this issue.
