### ISSUE TITLE
minify, increases the imagesize

### ISSUE THREAD

**Issue by nmitra6** [chenjuneking/quill-image-drop-and-paste#28]
I tried to minify a 1024x1024px jpg image of 48Kb size to 320x320px, type .jpg, quality 0.7, the resulting image is 52Kb. Roughly 1/9 th reduction in pixel data but resulting image size is bigger. When we are drawing an RGB formatted image on a canvas, there will be 33% increase because of transparency for same size, that can't be avoided as of now.  I think from canvas we can directly get Blob and we can read the initial image as Blob too. So internal logic of resizing could be lot more efficient.

**Comment by chenjuneking** [comment]
This looks interesting. For further compression of small pictures, I have not tested before, I will try the solution you mentioned.

**Comment by chenjuneking** [comment]
For some images that have been compressed by other ways, there is indeed a situation that the size increases after minify by this plugin. In this case, you can determine the size of the image before and after compression, and decide which one to upload. The implementation of this code may help you:

[Example of image upload](https://github.com/chenjuneking/quill-image-drop-and-paste/blob/d8a5f6e1a70f1a207fae7068aa224fb92c611258/example/nextjs-demo/pages/index.js#L23)
