### ISSUE TITLE
Any plans to make this lib work for angular?

### ISSUE THREAD

**Issue by bri1990** [chenjuneking/quill-image-drop-and-paste#29]
Initially I thought it would work for angular, however I can't get it to work. the following error keeps coming back

Error: Uncaught (in promise): TypeError: moduleClass is not a constructor
TypeError: moduleClass is not a constructor

also

`import * as QuillImageDropAndPaste from 'quill-image-drop-and-paste';`
gives an error, even though the module is installed. following error:
Cannot find module 'quill-image-drop-and-paste' or its corresponding type declarations. 

I thought that the following code worked, but it does not
```
const QuillImageDropAndPaste = require('quill-image-drop-and-paste');  
Quill.register('modules/imageDropAndPaste', QuillImageDropAndPaste);
```

any thoughts? 

i'm also using https://www.npmjs.com/package/ngx-quill

**Comment by chenjuneking** [comment]
Hi, I made a angular example, hope it can help you.
👉 [Angular Dmo](https://github.com/chenjuneking/quill-image-drop-and-paste/tree/master/example/angular-demo)
