### ISSUE TITLE
TypeError: moduleClass is not a constructor [nextjs]

### ISSUE THREAD

**Issue by TheDarkStrix** [chenjuneking/quill-image-drop-and-paste#30]
Hey guys ,
I am trying to implement drop and paste , i basically want catch image and upload to cloud instead of using base64 .

The code below is my current implementation . But I get the error `TypeError: moduleClass is not a constructor` .

Not sure what is wrong.

Any help is very much appreciated, thanks.

Versions: 
"react-quill": "^2.0.0-beta.2",
"quill": "^1.3.7",
"quill-image-drop-and-paste": "^1.2.5",

@chenjuneking  

``` javascript
import React, { useState, useRef, useEffect } from "react";

// KaTeX dependency
import katex from "katex";
import "katex/dist/katex.css";

// Quill dependency
const Quill =
  typeof window === "object" ? require("react-quill").Quill : () => false;
const ReactQuill =
  typeof window === "object" ? require("react-quill") : () => false;
import "react-quill/dist/quill.snow.css";
const QuillImageDropAndPaste =
  typeof window === "object"
    ? require("quill-image-drop-and-paste")
    : () => false;

// MathQuill dependency
import "jquery";
typeof window === "object"
  ? require("mathquill/build/mathquill.js")
  : () => false;
import "mathquill/build/mathquill.css";

const mathquill4quill =
  typeof window === "object" ? require("mathquill4quill") : () => false;
import "mathquill4quill/mathquill4quill.css";

//Global definition
if (typeof window !== "undefined") {
  window.Quill = Quill;
  window.katex = katex;
}

export default function QuillPage() {
  const [load, setLoad] = useState(true);
  const [value, setValue] = useState("");
  const quillRef = useRef();

  useEffect(() => {
    Quill.register("modules/imageDropAndPaste", QuillImageDropAndPaste);
    // window.Quill = Quill;
    window.katex = katex;

    const enableMathQuillFormulaAuthoring = mathquill4quill({ Quill, katex });
    console.log(window);
    enableMathQuillFormulaAuthoring(
      quillRef.current.editor,
      {
        operators: [
          ["\\pm", "\\pm"],
          ["\\sqrt{x}", "\\sqrt"],
          ["\\sqrt[n]{x}", "\\nthroot"],
          ["\\frac{x}{y}", "\\frac"],
          ["\\sum^{s}_{x}{d}", "\\sum"],
          ["\\prod^{s}_{x}{d}", "\\prod"],
          ["\\coprod^{s}_{x}{d}", "\\coprod"],
          ["\\int^{s}_{x}{d}", "\\int"],
          ["\\binom{n}{k}", "\\binom"],
          ["\\log{x}", "\\log"],
        ],

        displayHistory: true, // defaults to false
        historyCacheKey: "__my_app_math_history_cachekey_", // optional
        historySize: 20, // optional (defaults to 10)
      },
      quillRef.current.options
    );
    setLoad(false);
  }, [quillRef]);

  useEffect(() => {
    console.log(value);
  }, [value]);

  const imageHandler = () => {
    console.log("image");
  };

  return (
    <>
      <ReactQuill
        ref={quillRef}
        modules={{
          formula: true,
          imageDropAndPaste: {
            handler: imageHandler(),
          },
          toolbar: [["formula", "image"]],
        }}
        theme="snow"
        value={value}
        onChange={setValue}
      />
    </>
  );
}

```

**Comment by chenjuneking** [comment]
had you tried `import QuillImageDropAndPaste from "quill-image-drop-and-paste"` ?

**Comment by TheDarkStrix** [comment]
Yes sir ! 
![image](https://user-images.githubusercontent.com/18639879/129440269-72f80479-c272-400c-9f94-744e6a482603.png)

The same issue .

The only reason i used this is to make sure that this loads on frontend side rather than the backend side of things
```
const QuillImageDropAndPaste =
  typeof window === "object"
    ? require("quill-image-drop-and-paste")
    : () => false;
```

**Comment by nmitra6** [comment]
Same problem in Nuxt.js too ( ver: 1.2.5). All SSR framework will face the same issue.
In nuxt, any external library is added in plugins folder. For client-side code (window/document === 'object'), no import in vue pages work. "require" works properly for default exports. In this package ( ver 1.2.5) the ImageData constructor class is not added in default exports. In (ver: 1.2.1)  it  worked if ImageData class was added as an assignment. But it's totally unusable in nuxt now.

It will work if the following statement/variation can be incorporated somehow.

let QuillImageData = process.client  ? require('quill-image-drop-and-paste').ImageData : null

or require('quill-image-drop-and-paste/dist/quill-image-drop-and-paste') i.e from transpiled code

process.client (nuxt) is equiv to (typeof window === "object") or (typeof document === "object")

**Comment by chenjuneking** [comment]
@TheDarkStrix , try this:
```
const QuillImageDropAndPaste =
  typeof window === "object"
    ? require("quill-image-drop-and-paste").default
    : () => false;
```

**Comment by nmitra6** [comment]
Thanks Mr. Chen,

It’s working. My problem was with ImageData in custom handler, in Nuxt.js.

I solved it by,


const QuillImageData =

  process.client

    ? require("quill-image-drop-and-paste").ImageData

    : null;

USP of your module is added minification, Kindly upgrade to have a lower filesize after minification.

I see, how you solved the paste text problem. Very nice.
TypeScript datatypes are also a good improvement.

Keep up the good work.

Thanks a lot.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by chenjuneking** [comment]
Since this issue has been resolved, I closed it now.
If you have any problem, feel free to let me know.

**Comment by TheDarkStrix** [comment]
The issue still persists. 

I tried : 
```
const QuillImageDropAndPaste =
  typeof window === "object"
    ? require("quill-image-drop-and-paste").default
    : () => false;
```

```
const QuillImageDropAndPaste =
  typeof window === "object"
    ? require("quill-image-drop-and-paste").ImageDropAndPaste
    : () => false;
```
