### ISSUE TITLE
Is it possible to preserve the filename of pasted / dropped file

### ISSUE THREAD

**Issue by michalpokojski** [chenjuneking/quill-image-drop-and-paste#31]
I see in README that you create filename yourself, but is it possible to inherit it from pasted / dropped file?

**Comment by chenjuneking** [comment]
The dropped file has a file name, but some pasted files do not have a file name. Imagine you take a screenshot from the screen, and the screenshot is stored in the clipboard, it does not have a name. But for dropped file, we can support this feature, this will be in the next feature.
Thank you for your suggestion.

**Comment by chenjuneking** [comment]
support on v1.2.8

**Comment by michalpokojski** [comment]
Thanks! That will be very useful for me :)
