### ISSUE TITLE
How to support quill2?

### ISSUE THREAD

**Issue by YNestA** [chenjuneking/quill-image-drop-and-paste#35]

**Comment by chenjuneking** [comment]
this module had not been tested on quill2 yet.

**Comment by YNestA** [comment]
> this module had not been tested on quill2 yet.

In quill2, I have achieved it with the upload module.

**Comment by mambans** [comment]
> > this module had not been tested on quill2 yet.
> 
> In quill2, I have achieved it with the upload module.

Hello, which upload module did use?

**Comment by chenjuneking** [comment]
Since there's no more feedback, I'll close this issue.
