### ISSUE TITLE
Does not seem to work with Vue

### ISSUE THREAD

**Issue by PushyPants** [chenjuneking/quill-image-drop-and-paste#38]
I can't seem to get this up and running with Vue. I tried unsuccessfully to get it going in my own app and after trying different things over a few hours I decided to try and just get your example up and running to see what I'm doing wrong. 

I cloned the repot and went into the examples folder, into the vue folder and ran straight from your code and it's not working there either. 

None of the consoles you have set to run in the imageHandler fire and I threw a few debuggers in and around and node of them hit in the handler. Nothing from your code was modified beside adding the debugger.

**Comment by chenjuneking** [comment]
Hi, @PushyPants , try this: 

```bash
$ git clone https://github.com/chenjuneking/quill-image-drop-and-paste.git
$ cd quill-image-drop-and-paste && yarn install
$ cd example/vue-demo
$ yarn install
$ yarn start
```
then open your browser and visit `http://localhost:8080/`, drag and drop an image into the editor.

**Comment by PushyPants** [comment]
Thank you for your quick reply! I probably should have been more clear in the first message. I did install all dependencies (albeit through NPM). For good measure I installed yarn and followed your instructions,

While, in both scenarios, the app runs. The drag/drop and paste functionality does not fire the handler function. I've placed a debugger inside, at the top of the handler, and it is never reached. 

drag and drop does not result in an image in the editor, whereas paste will. But neither seem to fire the handler function. 

Is there a chance an update has created a breaking change since the demos were created?

**Comment by chenjuneking** [comment]
I'm sure the demo is working on my laptop😂, I use the newest chrome browser, and safari as well.
Here is my screen record: 
https://user-images.githubusercontent.com/4432938/143170902-b6d0a778-cb68-459e-b39f-9ff6e859d30a.mp4

What's your brower's version?
