### ISSUE TITLE
 rewrite the toolbar's insert image button error

### ISSUE THREAD

**Issue by simon-muyezhang** [chenjuneking/quill-image-drop-and-paste#40]
@chenjuneking rewrite the toolbar's insert image button error

![image](https://user-images.githubusercontent.com/10706610/167167623-0d2341c5-5392-43b0-a328-0ea20cbd983e.png)
![image](https://user-images.githubusercontent.com/10706610/167167695-6b1f06cb-c1b5-4ce1-90b9-5c0952bbf0ee.png)
It works with images under 100k, when image size is larger than 100kb, give me this error.
![image](https://user-images.githubusercontent.com/10706610/167168007-283b3feb-69df-4456-b986-e03c53b9de54.png)

**Comment by simon-zhangmuye** [comment]
@chenjuneking hi

**Comment by chenjuneking** [comment]
@simon-zhangmuye 
This bug had been fixed on v1.2.11, please update your package.
