### ISSUE TITLE
plugin not firing when copy image from web

### ISSUE THREAD

**Issue by iko16-haekal** [chenjuneking/quill-image-drop-and-paste#44]
hello i found some issue,

The plugin doesn't work when copy image from web, handler doesn't call at all

but its work when i copy from my local drive

I've tested it on Chrome on Windows 10

**Comment by chenjuneking** [comment]
@iko16-haekal , Thanks for your report.
I'd test on my laptop and coundn't reproduce this bug, could you apply more details?
This plugin coundn't copy & paste image from local drive by design, see [this issue](https://github.com/chenjuneking/quill-image-drop-and-paste/issues/16) for the reason.

**Comment by iko16-haekal** [comment]
@chenjuneking thanks for the response, and sorry for late reply,

i'm using 
"quill": "^1.3.7",
"quill-image-drop-and-paste": "^1.2.11",
"react-quill": "^2.0.0",

and here i provide my screen record
https://www.loom.com/share/d685b0e78b5c47a0bcca47d2afbdf9dd

as you can see if  copy image from local drive the handler will trigger and if  copy image from google image or other website the handler doesn't call at all

**Comment by parterburn** [comment]
Noticed this, too. If the image you copy using Chrome already has a remote URL it won't upload it to your own servers. It causes problems if you copy a private file (such as from Google Photos) and then paste it into Quill...the _people viewing_ the content won't have access to that remote URL, but you wouldn't have any idea because the _editor_ can see it just fine.

**Comment by chenjuneking** [comment]
Hi @iko16-haekal , this issue has been fixed on v1.2.13

**Comment by iko16-haekal** [comment]
wow, now its working, thanks a lot

**Comment by iko16-haekal** [comment]
hi @chenjuneking, sorry after the update on v1.2.13 i found new issues

i cant paste an url or link anymore

here i provide my screen record 
https://www.loom.com/share/729075717b3e4c3595a1234efa7b6952

**Comment by chenjuneking** [comment]
> hi @chenjuneking, sorry after the update on v1.2.13 i found new issues
> 
> i cant paste an url or link anymore
> 
> here i provide my screen record https://www.loom.com/share/729075717b3e4c3595a1234efa7b6952

sorry for the trouble, I'd published a new release, please try v1.2.14

**Comment by iko16-haekal** [comment]
nice, thanks
