### ISSUE TITLE
Network Request happens on every url added

### ISSUE THREAD

**Issue by MuaazOsaidTahir** [chenjuneking/quill-image-drop-and-paste#46]
A network request is sent whenever a URL is pasted in the editor.
& if the URL is of an image it is replaced with an image. which is not the behavior I need.
Can there be any workaround to run this function **urlIsImage** optionally?
Can a parameter be passed to use this functionality depending on the use case?

![image](https://user-images.githubusercontent.com/66464591/232033548-18759b67-b484-4edd-aa98-723cf290a366.png)

**Comment by chenjuneking** [comment]
Hello, @MuaazOsaidTahir , please set the `autoConvert` option to `false` and make sure the library's version is `^v1.3.0`.
```js
var quill = new Quill('#editor-container', {
  modules: {
    imageDropAndPaste: {
      autoConvert: false,
      handler: imageHandler,
    },
  },
  placeholder: 'Copy & paste, or drag an image here...',
  // ...
})
```

**Comment by MuaazOsaidTahir** [comment]
Thank you @chenjuneking . Will test it out & let you know.
Closing the issue for now & if there'll be any query I'll definitely ask it later.
