### ISSUE TITLE
In react-quill2 Quill.register('modules/imageDropAndPaste', QuillImageDropAndPaste) failed with register of undefined

### ISSUE THREAD

**Issue by udaya-reddy** [chenjuneking/quill-image-drop-and-paste#47]
On debugging Quill.register('modules/imageDropAndPaste', QuillImageDropAndPaste) is taking second argument as undefined

![image](https://user-images.githubusercontent.com/67152550/234044641-439c0402-5b46-408a-a139-da0ada94364a.png)

Here the target comes as undefined. even if present it is looking for target.register() function...

![image](https://user-images.githubusercontent.com/67152550/234044950-53c323b6-cddf-47f3-9cd0-71c2248ab945.png)

Not sure if I am missing anything in the setup.

**Comment by chenjuneking** [comment]
Hi @udaya-reddy , could you supply more details?

**Comment by chenjuneking** [comment]
Since there's no more feedback, I'll close this issue.

**Comment by chenjuneking** [comment]
Since there's no more feedback, I'll close this issue.
