### ISSUE TITLE
Paste related questions

### ISSUE THREAD

**Issue by chenxch** [chenjuneking/quill-image-drop-and-paste#48]
# Version
`quill-image-drop-and-paste`: '1.2.9'

# Question

Paste related questions:
1. paste delayed response
2. wrong paste

## paste delayed response
1. paste `https://github.surmon.me/vue-quill-editor`
2. You will find this without any problem, then empty the text box
3. paste `https://www.vuescript.com/quill-editor-component-vue2/`
4. You will notice a noticeable delay of a few seconds before the content is filled.

## wrong paste
1. paste `https://www.vuescript.com/quill-editor-component-vue2/`
2. Copy pasteboard contents elsewhere as `quill-editor`
3. In the text box, Ctrl+A selects all the text, and then pastes it, you will find that the content does not match the clipboard.

![paste](https://user-images.githubusercontent.com/23251408/234828662-3ed849a1-2f04-4cf8-8491-24d22edbbc5d.gif)

**Comment by chenjuneking** [comment]
Hi @chenxch.
Thanks for your report. Regarding to your question, I will make the following explanation, hoping to answer your question.

1. **paste delayed response**
Erery URL-like pasted content will cause a network request for [this reason](https://github.com/chenjuneking/quill-image-drop-and-paste/issues/45#issuecomment-1296444379), it's a feature of this module --- automatically convert the link into an image and insert it into the editor while you paste an image's link. So if you meet a network issue, for example, it takes 1 second to response the request, that will make you feel the paste delay for sure.
If you dont like this feature, it can be disabled by passing `autoConvert: false` option on `^v1.3.0`. it will not detect the pasted content anymore.

2. **wrong paste**
Sorry, I can't reproduce this problem.

**Comment by chenxch** [comment]
Thank you for your feedback, I am very sorry, my version at that time should be 1.2.9, and now I have upgraded to 1.3.0. After local testing, it is normal, and I am currently waiting for QA acceptance. Then this is the reproduction screen recording of the second scene mentioned earlier.
![paste2](https://user-images.githubusercontent.com/23251408/236432424-715a6242-c820-4947-9fcc-818583b50d10.gif)
