### ISSUE TITLE
With the release of Quill 2.0, Parchment image blot gets triggered regardless of if your handler is set

### ISSUE THREAD

**Issue by phillipwildhirt** [chenjuneking/quill-image-drop-and-paste#53]
Pretty simple. Upgrade to Quill 2.0, drag over an image and even if your handler is set, Parchment Image Blot runs trying to create the dropped image.

It's pretty clear to me that minified distributed Quill 1.3.7 was actually using a different version of quill-delta. So the issue may lie there rather than once we get to the parchment script.

Quill 2.0.1
Quill-Delta 5.1.0
Angular 17.3.7
Ngx-Quill 25.3.2

**Comment by phillipwildhirt** [comment]
Appears as though quill 2.0.2 has fixed this with Bug Fix:

> Ignore pasting images when image format is disallowed by @luin in https://github.com/slab/quill/pull/4202

**Comment by linxianxi** [comment]
How to resolve it? How to disable quill's default behavior？

**Comment by phillipwildhirt** [comment]
We pass a handler to it as per the docs

> Finally
> If you didnot config a image handler, it will insert the image with dataURL into the quill editor directory after your drop/paste.
