### ISSUE TITLE
Why drop Image HandleDrop isn't 'image' type?

### ISSUE THREAD

**Issue by wss534857356** [chenjuneking/quill-image-drop-and-paste#54]
https://github.com/chenjuneking/quill-image-drop-and-paste/blob/ade89cf623e6c479d49fbf9fe2acc7abce029d5b/src/ImageDropAndPaste.ts#L87

it should be 'image'
```ts
this.insert.call(this, utils.resolveDataUrl(dataUrl, type), 'image')
```

**Comment by dalexander-trc** [comment]
Without investigating too much, I'd wager it's a variable to ensure that any custom blots that might extend/overwrite image are preserved.

**Comment by wss534857356** [comment]
> Without investigating too much, I'd wager it's a variable to ensure that any custom blots that might extend/overwrite image are preserved.

sure, I agree you point. But in some case, image file may not include 'image' type

**Comment by chenjuneking** [comment]
@wss534857356 , This is due to support for the `autoConvert` feature, which automatically inserts an image into the editor when you paste an image URL that is of type text/plain, not image.
