### ISSUE TITLE
Script tag file not working

### ISSUE THREAD

**Issue by gigi199596** [chenjuneking/quill-image-drop-and-paste#6]
Hey,
Nice plugin mate :)

I actually tried to use it with the script tag and fall into an error with your demo.
To fix it I changed line 31 by:
`var ImageDropAndPaste = exports.ImageDropAndPaste = function() {`
and removed the line 105:
`exports.default=ImageDropAndPaste;`
lines numbers are after pretty printing the file.

I just did that by comparing to the other drop and paste plugin and fixed the problem.
So I would like to know why because I don't have much knowledge of React and Vue 😄 

Hope it helps,

Gilles

**Comment by chenjuneking** [comment]
> Hey,
> Nice plugin mate :)
> 
> I actually tried to use it with the script tag and fall into an error with your demo.
> To fix it I changed line 31 by:
> `var ImageDropAndPaste = exports.ImageDropAndPaste = function() {`
> and removed the line 105:
> `exports.default=ImageDropAndPaste;`
> lines numbers are after pretty printing the file.
> 
> I just did that by comparing to the other drop and paste plugin and fixed the problem.
> So I would like to know why because I don't have much knowledge of React and Vue 😄
> 
> Hope it helps,
> 
> Gilles

Thanks for your report, @gigi199596 .
I use babel.js to compile ES6 source code to ES5.

On ES6:
`
expoet default class ImageDropAndPaste {
}
`

will be compiled to ES5 like this:
`
exports.default = ImageDropAndPaste;
`

when write into a script tag version of js file: quill-image-drop-and-paste.min.js, I insert some code both on the top and end:
`
(function(){var exports={};
MINIFIED_JS
window.Quill.register('modules/imageDropAndPaste',exports.ImageDropAndPaste)})();
`
which **MINIFIED_JS** should be replaced by the compiled code.

that error must comes from the end part:
`
window.Quill.register('modules/imageDropAndPaste',exports.ImageDropAndPaste)})();
`

it should be
`
window.Quill.register('modules/imageDropAndPaste',exports.default)})();
`

I had fixed it and regenerate a new version of quill-image-drop-and-paste.min.js, let me know if you still have questions.
